spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.147.216:3306/store?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 60000

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.bookmall.Dao : debug
